version: "3.8"

services:
   hallucination-hunter:
      build:
         context: .
         dockerfile: Dockerfile
      volumes:
         - ./models:/app/models
         - ./data:/app/data
      ports:
         - "8000:8000" # API
         - "8501:8501" # Streamlit UI
      environment:
         - MODULE_NAME=hallucination_hunter.api.main
         - VARIABLE_NAME=app
         - API_PORT=8000
         - UI_PORT=8501
         - WANDB_API_KEY=${WANDB_API_KEY:-}
         - MODEL_PATH=${MODEL_PATH:-models/hallucination_classifier}
         - CONFIDENCE_THRESHOLD=${CONFIDENCE_THRESHOLD:-0.7}
      restart: unless-stopped
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
         interval: 30s
         timeout: 10s
         retries: 3
         start_period: 5s

   # Optional database for storing prediction history
   # db:
   #   image: postgres:14-alpine
   #   volumes:
   #     - postgres_data:/var/lib/postgresql/data/
   #   environment:
   #     - POSTGRES_USER=hunter
   #     - POSTGRES_PASSWORD=hunter
   #     - POSTGRES_DB=hallucination_hunter
   #   ports:
   #     - "5432:5432"
# volumes:
#   postgres_data:
